sudo: true
dist: trusty
install:
- sudo apt-get --yes install autoconf libtool nasm
- npm install
- wget https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_0.76.5_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
script:
- hugo
cache:
  directories:
  - node_modules